### ISSUE TITLE
Tailnet API key expiry

### ISSUE THREAD

**Issue by Edzilla2000** [marc1307/tailscale-cloudflare-dnssync#18]
Hi, 
I see that in the Tailscale console the maximum lifetime of an API key is 90 days.
Do you manually create a new one every three month or do you have a better solution for this?
Thanks!

**Comment by marc1307** [comment]
Hi, this issue was been solved thanks to @Lifeismana

The script now support Oauth for the API authentication, the Oauth credentials do not expire (currently).
